### ISSUE TITLE
ORDENS DE SERVIÇO - INCLUIR OS

### ISSUE THREAD

**Issue by luizhgirolometto** [luizhgirolometto/offcina#5]
LABEL VALOR -> MUDAR ELA, COLOCAR EMBAIXO DO CAMPO OBSERVAÇÕES OU EM OUTRO LUGAR MELHOR, DEIXAR BLOQUEADO PARA NINGUÉM PODER EDITAR ESTE CAMPO, POIS O MESMO É A SOMA DOS ITENS.

LABEL VALOR PAGO - DEIXAR PADRÃO COM VALOR 0 OU NA HORA DE SALVAR A ORDEM DE SERVIÇO QUE O CAMPO DEVE SER INFORMADO 0, CASO NÃO TENHA SIDO FEITO PAGAMENTO.

NA HORA DA IMPRESSÃO O VALOR PAGO NÃO APARECE EM LUGAR NENHUM, NÃO DESCONTA DO TOTAL

**Comment by Pilonetto** [comment]
LABEL VALOR -> Realocado para o fim da tela, antes dos itens. Tambem alterado para ficar como somente leitura.
LABEL VALOR PAGO -> Alterado para o padrao 0.

Corrigida a impressao
